arguments:
  parameters:
    - name: application-name
      value: pipeline1-app1
    - name: application-name-2
      value: pipeline1-app2
    - name: revision
      value: HEAD
    - name: argocd-server-address
      value: 35.193.141.13:80
    - name: argocd-credentials-secret
      value: argocd-credentials-secret
